[book]
authors = ["Matheus Rocha"]
language = "pt-BR"
multilingual = false
src = "src"
title = "receitas.show"

[output.html]
additional-css = ["./theme/catppuccin.css"]
default-theme = "latte"
preferred-dark-theme = "macchiato"
git-repository-url = "https://github.com/mrocha98/receitas.show"
edit-url-template = "https://github.com/mrocha98/receitas.show/edit/main/{path}"
